SUBROUTINE CHEGADA
use, intrinsic:: iso_fortran_env, only: stdin=>input_unit
INTEGER KK,ND22,N,NI,II,I,NZ,NR,NA,NCG,NUMR,NRZ1,NRZ2,NRR,NRG,ZV,RV,AV,ZV_E,RV_E,AV_E
INTEGER ZV_C,RV_C,AV_C,ZV_G,RV_G,AV_G,ZV_A,RV_A,AV_A
INTEGER NZ1,NZ1_LASER,NZ2,NUR,NG,NSZ1,NSZ1_LASER,NSZ2,NSR,NSG,PACOTE,DIR,MIST

DOUBLE PRECISION II1,TG,DIMZ,DIMR,DIMCG,DELZ,DELR,NP_Z,NP_R,NP,W,TREF,TE,FI,BE,GA,Z,R,AL
DOUBLE PRECISION Z_C,R_C,AL_C,Z_E,R_E,AL_E,Z_G,R_G,AL_G,ZV1,RV1,ZV_E1,RV_E1,ZV_C1,RV_C1,ZV_G1,RV_G1,K
DOUBLE PRECISION D,DN,DFI,DSEN,DCOS,DCOSI,DNIT1,DNIT2,DNI,DFII,FIIPT,FIRP
DOUBLE PRECISION DCOSRP2T,DRPT,DCOSRNT,DNRNT,DRNT,FIRPT,FIRPTI,TERP,BE_I,GA_I
DOUBLE PRECISION TERPI,DNRP,DFIRP,DSENI,DCOSIT,DCOSIT1,FI_I,TE_I
DOUBLE PRECISION X,Y,X_C,Y_C,C,DX,DY,DY1,DY2,DDY1,DDY2,DZ,DXY,K1,K2,K3,K4
DOUBLE PRECISION X1,X2,Y_C1,Y_C2,PI 
DOUBLE PRECISION PZ_T1,PZ_T2,PZ_T3,PZ_T4,PZ_T5,PZ_T6,PZ_T7,PZ_T8,PZ_T9 
DOUBLE PRECISION CE1,CE2,CE3,CEE,KC1,KC2,KC3,K_C,PW,PC,PWC,FPAG,K_ABS
DOUBLE PRECISION E0,R0,MU_T,FWHM,P_LASER,SINAL

!REAL*8 CABS_NANO, CEXT_NANO, CESP_NANO, R_N, FV, R_VC, FV_VC

COMMON II1,TG,DIMZ,DIMR,DIM_ALPHA,DIMCG,DELZ,DELR,NP_Z,NP_R,NP,W,TREF,TE,FI,BE,GA,Z,R,AL
COMMON Z_C,R_C,AL_C,Z_E,R_E,AL_E,Z_G,R_G,AL_G,ZV1,RV1,ZV_E1,RV_E1,ZV_C1,RV_C1,ZV_G1,RV_G1,K
COMMON D,DN,DFI,DSEN,DCOS,DCOSI,DNIT1,DNIT2,DNI,DFII,FIIPT,FIRP
COMMON DCOSRP2T,DRPT,DCOSRNT,DNRNT,DRNT,FIRPT,FIRPTI,TERP,BE_I,GA_I
COMMON TERPI,DNRP,DFIRP,DSENI,DCOSIT,DCOSIT1,FI_I,TE_I
COMMON X,Y,X_C,Y_C,C,DX,DY,DY1,DY2,DDY1,DDY2,DZ,DXY,K1,K2,K3,K4
COMMON X1,X2,Y_C1,Y_C2,PI 
COMMON PZ_T1,PZ_T2,PZ_T3,PZ_T4,PZ_T5,PZ_T6,PZ_T7,PZ_T8,PZ_T9 
COMMON CE1,CE2,CE3,CEE,KC1,KC2,KC3,K_C,PW,PC,PWC,FPAG,K_ABS
COMMON E0,R0,MU_T,FWHM,P_LASER
COMMON KK,ND22,N,NI,II,I,NZ,NR,NA,NCG,NUMR,NRZ1,NRZ2,NRR,NRG,ZV,RV,AV,ZV_E,RV_E,AV_E
COMMON ZV_C,RV_C,AV_C,ZV_G,RV_G,AV_G,ZV_A,RV_A,AV_A
COMMON NZ1,NZ1_LASER,NZ2,NUR,NG,NSZ1,NSZ1_LASER,NSZ2,NSR,NSG,PACOTE,DIR,MIST
!COMMON CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC


!WRITE(*,*)'CHEGADA',PACOTE
!PAUSE   

!WRITE(*,*)'CHEGADA=CERTO'

! MUDANCA DE REFERENCIAL
D=1.D0 ! distancia arbitraria percorrida pelo foton 
DN=D*SIN(TE) ! componente da distancia d na direcao normal ao plano de onde o foton saiu 
DFI=D*COS(TE) ! componente da disancia d na direcao paralela a do plano de onde o foton saiu
DSEN=DFI*SIN(FI) ! componente de dfi na direcao do seno
DCOS=DFI*COS(FI) ! componente de dfi na direcao do coseno
! Projecoes das distancias em planos paralelos e normais ao do referencial principal
! r referencial principal 
! n normal, rn normal ao referencial principal
! p paralelo, rp paralelo ao referencial principal
! t temporario, antes do angulo ga ser considerado.
DCOSRPT=DCOS*COS(BE)
DSENRPT=DSEN
DNRPT=DN*SIN(BE)
DCOSRP2T=DCOSRPT+DNRPT
DRPT=(DCOSRP2T**2.D0+DSENRPT**2.D0)**.5D0 ! � sempre positivo
DCOSRNT=DCOS*SIN(-BE)
DNRNT=DN*COS(BE)
DRNT=DCOSRNT+DNRNT
FIRPT=ATAN(DSENRPT/DCOSRP2T)


IF (DCOSRP2T .GT. 0.d0) THEN
   FIRP=FIRPT+GA
   FIRPTI=FIRPT

!IF ( ABS(ABS(FIRP) - PI/2.d0) < 1.D-3) Then

!   SINAL = ((FIRP**2.d0)**.5)/FIRP

!   FIRP = SINAL*(PI/2.D0 + 1.D-3)

!ENDIF

ENDIF

IF (DCOSRP2T .LE. 0.d0) THEN
   FIRP=PI+FIRPT+GA
   FIRPTI=FIRPT

!IF ( ABS(ABS(FIRP) - 3.D0*PI/2.d0) < 1.D-3) Then

!   SINAL = ((FIRP**2.d0)**.5)/FIRP

!   FIRP = SINAL*(3.D0*PI/2.D0 + 1.D-3)

!ENDIF

ENDIF



TERP=ATAN(DRNT/DRPT)

!IF ( ABS(TAN(TERP)) < 1.D-1) Then

!   SINAL = ((TERP**2.d0)**.5)/TERP

!   TERP = TERP + SINAL*1.d-3 

!ENDIF

X=DIMR+R*COS(AL)
Y=DIMR+R*SIN(AL)
C = TAN(FIRP)


K4=Y-C*X-DIMR
K1=C**2.D0+1.D0
K2=2.D0*C*K4-2.D0*DIMR
K3=K4**2.D0
X1=(-K2+(K2**2.D0-4.D0*K1*K3)**.5D0)/(2.D0*K1)
X2=(-K2-(K2**2.D0-4.D0*K1*K3)**.5D0)/(2.D0*K1)

IF (COS(FIRP)>=0) THEN
   X_C=X1
ENDIF
IF (COS(FIRP)<0) THEN
   X_C=X2
ENDIF

!COMPL=(1.D0-2.D0)**.5D0 !VARI'AVEL NAO APARECE EM NENHUM LUGAR DO CODIGO
Y_C1=DIMR+(DIMR**2.D0-(X_C-DIMR)**2.D0)**.5D0
Y_C2=DIMR-(DIMR**2.D0-(X_C-DIMR)**2.D0)**.5D0
DX=X_C-X
DY=DX*TAN(FIRP)
DY1=Y_C1-Y
DY2=Y_C2-Y
DDY1=DY1-DY
DDY2=DY2-DY

IF (ABS(DDY1)<ABS(DDY2)) THEN
   Y_C=Y_C1
ELSE
   Y_C=Y_C2
ENDIF
DXY=((X_C-X)**2.D0+(Y_C-Y)**2.D0)**.5D0
DZ=DXY*TAN(TERP)
Z_C=Z+DZ
BE_I=PI/2.D0
IF (X_C>DIMR) THEN
   GA_I=ASIN((Y_C-DIMR)/DIMR)+PI
ENDIF   
IF (X_C<DIMR) THEN
   GA_I=-ASIN((Y_C-DIMR)/DIMR)
ENDIF
R_C=DIMR

!PACOTE CHEGA NA SUPERFICIE Z2
IF (Z_C .GE. DIMZ) THEN
   DZ=DIMZ-Z
   DXY=DZ/TAN(TERP)
   DX=DXY*COS(FIRP)
   DY=DXY*SIN(FIRP)
   Z_C=DIMZ
   X_C=X+DX
   Y_C=Y+DY
   BE_I=PI
   GA_I=0.D0
   R_C=((X_C-DIMR)**2.D0+(Y_C-DIMR)**2.D0)**.5D0
ENDIF
!PACOTE CHEGA NA SUPERFICIE Z1 
IF (Z_C .LE. 0.D0) THEN
   DZ=-Z
   DXY=DZ/TAN(TERP)
   DX=DXY*COS(FIRP)
   DY=DXY*SIN(FIRP)
   Z_C=0.D0
   X_C=X+DX
   Y_C=Y+DY
   BE_I=0.D0
   GA_I=0.D0
   R_C=((X_C-DIMR)**2.D0+(Y_C-DIMR)**2.D0)**.5D0
ENDIF


      IF (Y_C .GT. DIMR) THEN
         
         IF (X_C .GT. DIMR) THEN

            AL_C=ATAN((DIMR-Y_C)/(DIMR-X_C))

         ENDIF

         IF (X_C .LT. DIMR) THEN

            AL_C= PI + ATAN((DIMR-Y_C)/(DIMR-X_C))

         ENDIF

      ENDIF


      IF (Y_C .LT. DIMR) THEN
         
         IF (X_C .GT. DIMR) THEN

            AL_C= 2.D0*PI + ATAN((DIMR-Y_C)/(DIMR-X_C))

         ENDIF

         IF (X_C .LT. DIMR) THEN

            AL_C= PI + ATAN((DIMR-Y_C)/(DIMR-X_C))

         ENDIF

      ENDIF

      IF (X_C .EQ. DIMR) THEN 

         IF (Y_C .GE. DIMR) THEN 

            AL_C = PI/2.D0

         ENDIF

         IF (Y_C .LT. DIMR) THEN 

            AL_C = 3.D0*PI/2.D0

         ENDIF

      ENDIF

      IF (Y_C .EQ. DIMR) THEN 

         IF (X_C .GE. DIMR) THEN 

            AL_C = 0.D0

         ENDIF

         IF (X_C .LT. DIMR) THEN 

            AL_C = PI

         ENDIF

      ENDIF



!AL_C=ASIN((Y_C-DIMR)/R_C)
!IF (X_C>=DIMR) THEN
 !  IF (Y_C>=DIMR) THEN
 !     AL_C=AL_C
 !  ENDIF
 !  IF (Y_C<DIMR) THEN
 !     AL_C=2.D0*PI+AL_C
 !  ENDIF
!ENDIF
!IF (X_C<DIMR) THEN
!   AL_C=PI-AL_C
!ENDIF

!AL_C=ATAN((DIMR-Y_C)/(DIMR-X_C))
!IF (X_C>DIMR) THEN
!   AL_C = PI + AL_C
!ELSE
!   IF (Y_C>DIMR ) THEN
!      AL_C = 2.D0*PI + AL_C
!   ENDIF
!ENDIF
 

!write(*,*)'c',c/1.d14,FIRP,atan(FIRP)
!write(*,*)'CHEGADA1',K1,K2,K3
!write(*,*)'CHEGADA3',X_C,Z_C,R_C,AL_C
!read(stdin,*)
!endif

!write(*,*)''


!read(stdin,*)

! CALCULO DO ANGULO DE INCIDENCIA
TERPI=-TERP
FIRPI=FIRP+PI
D=1.D0
DNRP=D*SIN(TERPI) 
DFIRP=D*COS(TERPI) 
DSENI=DFIRP*SIN(FIRPI-GA_I)
DCOSIT=DFIRP*COS(FIRPI-GA_I) 
DCOSIT1=-DNRP*COS(PI/2-BE_I)
DCOSIT2=DCOSIT*COS(-BE_I)
DCOSI=DCOSIT1+DCOSIT2
DNIT1=DNRP*COS(BE_I)
DNIT2=DCOSIT*SIN(BE_I)
DNI=DNIT1+DNIT2
DFII=(DSENI**2.D0+DCOSI**2.D0)**.5D0
FIIPT=ATAN(DSENI/DCOSI)
IF (DCOSI>0) THEN
   FI_I=FIIPT
ENDIF
IF (DCOSI<0) THEN
   FI_I=FIIPT+PI
ENDIF
TE_I=ATAN(DNI/DFII)
! fi_i � o �ngulo fi de incid�ncia no referencial do plano de incid�ncia.
! te_i � o �ngulo te de incid�ncia no referencial do plano de incid�ncia.


END SUBROUTINE CHEGADA
