SUBROUTINE CILINDRO_NUCLEO(DDZ,P_Z,DDR,R_M,P_R,N_G_M,N_R_M,N_Z1_M,N_Z2_M,&
&N_LASER1,Q_LASER1,Z_LASER1,R_LASER1,AL_LASER1,GA_LASER1,BE_LASER1,A_M,V_M,EMIT_M,EAB2,&
&T_M,E_M,D_M,CA_CINZA,CESP,QA,QS,DIMR_LASER1,&
&CEXT,NANO_IN_VOLUME,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,G,N_TE,CPART,CTEC,raio)

INTEGER KK,ND22,N,NI,II,I,NZ,NR,NA,NCG,NUMR,NRZ1,NRZ2,NRR,NRG,ZV,RV,AV,ZV_E,RV_E,AV_E
INTEGER ZV_C,RV_C,AV_C,ZV_G,RV_G,AV_G,ZV_A,RV_A,AV_A
INTEGER NZ1,NZ1_LASER,NZ2,NUR,NG,NSZ1,NSZ1_LASER,NSZ2,NSR,NSG,PACOTE,DIR,MIST
INTEGER CONT1,CONT2,N_TE,CPART,CTEC,N_LASER1

DOUBLE PRECISION II1,TG,DIMZ,DIMR,DIMCG,DELZ,DELR,NP_Z,NP_R,NP,W,TREF,TE,FI,BE,GA,Z,R,AL
DOUBLE PRECISION Z_C,R_C,AL_C,Z_E,R_E,AL_E,Z_G,R_G,AL_G,ZV1,RV1,ZV_E1,RV_E1,ZV_C1,RV_C1,ZV_G1,RV_G1,K
DOUBLE PRECISION D,DN,DFI,DSEN,DCOS,DCOSI,DNIT1,DNIT2,DNI,DFII,FIIPT,FIRP
DOUBLE PRECISION DCOSRP2T,DRPT,DCOSRNT,DNRNT,DRNT,FIRPT,FIRPTI,TERP,BE_I,GA_I
DOUBLE PRECISION TERPI,DNRP,DFIRP,DSENI,DCOSIT,DCOSIT1,FI_I,TE_I
DOUBLE PRECISION X,Y,X_C,Y_C,C,DX,DY,DY1,DY2,DDY1,DDY2,DZ,DXY,K1,K2,K3,K4
DOUBLE PRECISION X1,X2,Y_C1,Y_C2,PI 
DOUBLE PRECISION PZ_T1,PZ_T2,PZ_T3,PZ_T4,PZ_T5,PZ_T6,PZ_T7,PZ_T8,PZ_T9 
DOUBLE PRECISION CE1,CE2,CE3,CEE,KC1,KC2,KC3,K_C,PW,PC,PWC,FPAG,K_ABS
DOUBLE PRECISION E0,R0,MU_T,FWHM,P_LASER,DIMR_LASER1,Q_LASER1
REAL*8 Z_LASER1,R_LASER1,A_LASER1,AL_LASER1,GA_LASER1,BE_LASER1

REAL*8 CABS_NANO,CEXT_NANO,CESP_NANO,R_N,FV,R_VC,FV_VC,G,QA,QS

DIMENSION NANO_IN_VOLUME(NZ+2,NR+2,NA) 
DIMENSION N_G_M(NZ+2,NR+2,NA),N_R_M(NZ+2,NR+2,NA),N_Z1_M(NZ+2,NR+2,NA)
DIMENSION N_Z2_M(NZ+2,NR+2,NA),N_M_LASER(NZ+2,NR+2,NA)
DIMENSION DDZ(NZ+2),P_Z(NZ+2)
DIMENSION DDR(NR+2),R_M(NR+2),P_R(NR+2)
DIMENSION Q_LASER(NZ+2,NR+2,NA)
DIMENSION A_M(NZ+2,NR+2,NA),V_M(NZ+2,NR+2,NA),EMIT_M(NZ+2,NR+2,NA)
DIMENSION EAB2(NZ+2,NR+2,NA),T_M(NZ+2,NR+2,NA)
DIMENSION E_M(NZ+2,NR+2,NA),D_M(NZ+2,NR+2,NA)
DIMENSION CESP(NZ+2,NR+2,NA),CEXT(NZ+2,NR+2,NA),CA_CINZA(NZ+2,NR+2,NA)
!DIMENSION E_EMAB(NZ+2,NANR+2,NZ+2,NR+2)


character(50) raio

COMMON II1,TG,DIMZ,DIMR,DIM_ALPHA,DIMCG,DELZ,DELR,NP_Z,NP_R,NP,W,TREF,TE,FI,BE,GA,Z,R,AL
COMMON Z_C,R_C,AL_C,Z_E,R_E,AL_E,Z_G,R_G,AL_G,ZV1,RV1,ZV_E1,RV_E1,ZV_C1,RV_C1,ZV_G1,RV_G1,K
COMMON D,DN,DFI,DSEN,DCOS,DCOSI,DNIT1,DNIT2,DNI,DFII,FIIPT,FIRP
COMMON DCOSRP2T,DRPT,DCOSRNT,DNRNT,DRNT,FIRPT,FIRPTI,TERP,BE_I,GA_I
COMMON TERPI,DNRP,DFIRP,DSENI,DCOSIT,DCOSIT1,FI_I,TE_I
COMMON X,Y,X_C,Y_C,C,DX,DY,DY1,DY2,DDY1,DDY2,DZ,DXY,K1,K2,K3,K4
COMMON X1,X2,Y_C1,Y_C2,PI 
COMMON PZ_T1,PZ_T2,PZ_T3,PZ_T4,PZ_T5,PZ_T6,PZ_T7,PZ_T8,PZ_T9 
COMMON CE1,CE2,CE3,CEE,KC1,KC2,KC3,K_C,PW,PC,PWC,FPAG,K_ABS!
COMMON E0,R0,MU_T,FWHM,P_LASER
COMMON KK,ND22,N,NI,II,I,NZ,NR,NA,NCG,NUMR,NRZ1,NRZ2,NRR,NRG,ZV,RV,AV,ZV_E,RV_E,AV_E
COMMON ZV_C,RV_C,AV_C,ZV_G,RV_G,AV_G,ZV_A,RV_A,AV_A
COMMON NZ1,NZ1_LASER,NZ2,NUR,NG,NSZ1,NSZ1_LASER,NSZ2,NSR,NSG,PACOTE,DIR,MIST
!COMMON CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC




!CALL RANDOM_SEED

PI=ACOS(-1.D0)
NZV_G=0

!CALL DADOS_CILINDRO

PWC=PW+PC

P_Z(1)=0.D0
P_Z(NZ+2)=DIMZ
P_R(1)=0
P_R(NR+2)=DIMR


!CALL DADOS_CILINDRO

IF (DIMR/NR<DIMZ/NZ) THEN 
   DIMCG=DIMR
   NCG=FPAG*NR
ELSE
   DIMCG=DIMZ
   NCG=FPAG*NZ
ENDIF 
  
WRITE(*,*)'DADOS ARMAZENADOS'
WRITE(*,*)''
CALL CPU_TIME(TIME_END)
TEMPO1=TIME_END-TIME_BEGIN
WRITE(*,*)'TEMPO1=',TEMPO1


WRITE(*,*)'CALCULOS EM EXECUCAO'

N=500
DIMAL=2*PI
DELZ=DIMZ/NZ
DELR=DIMR/NR
DELAL=2*PI


DO ZV=1,NZ+2
   DDZ(ZV)=0
ENDDO
DO RV=1,NR+2
   DDR(RV)=0
   R_M(RV)=0
ENDDO

DO ZV=2,NZ+1
   DDZ(ZV)=DIMZ/NZ
ENDDO

DO RV=2,NR+1
   DDR(RV)=DIMR/NR
   R_M(RV)=R_M(RV-1)+DDR(RV)
ENDDO
R_M(NR+2)=DIMR

DO ZV=1,NZ+2
   DO RV=1,NR+2
      DO AV=1,NA
         V_M(ZV,RV,AV)=0.D0
      ENDDO
   ENDDO
ENDDO
  
DO RV=1,NR+2
   DO AV=1,NA
      A_M(1,RV,AV)=0.D0
      A_M(NZ+2,RV,AV)=0.D0
   ENDDO
ENDDO

DO ZV=1,NZ+2
   DO AV=1,NA
      A_M(ZV,NR+2,AV)=0.D0
   ENDDO
ENDDO


!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
DO ZV=2,NZ+1
   DO RV=2,NR+1
      DO AV=1,NA
         V_M(ZV,RV,AV)=PI*DDZ(ZV)*(R_M(RV)**2D0-R_M(RV-1)**2D0)/NA
      ENDDO
   ENDDO
ENDDO

DO RV=2,NR+1
   DO AV=1,NA
      A_M(1,RV,AV)=PI*(R_M(RV)**2D0-R_M(RV-1)**2D0)/NA
      A_M(NZ+2,RV,AV)=A_M(1,RV,AV)
   ENDDO
ENDDO

DO ZV=2,NZ+1
   DO AV=1,NA
      A_M(ZV,NR+2,AV)=R_M(NR+2)*2D0*PI*DDZ(ZV)/NA
   ENDDO
ENDDO
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

DO ZV=1,NZ+2
   DO RV=1,NR+2
      DO AV=1,NA
         EMIT_M(ZV,RV,AV)=0.D0
         EAB2(ZV,RV,AV)=0.D0
      ENDDO
   ENDDO
ENDDO


!DO ZV1=1,NZ+2
!   DO RV1=1,NR+2
!      DO AV1=1,NA
!         DO ZV2=1,NZ+2
!            DO RV2=1,NR+2
!               DO AV2=1,NA
	          !E_EMAB(ZV1,RV1,AV1,ZV2,RV2,AV2)=0.D0
!               ENDDO
!            ENDDO
!         ENDDO
!      ENDDO
!   ENDDO
!ENDDO





! EMISSAO DE PACOTES PELO LASER

NSZ1_LASER=0

NZ1_LASER = N_LASER1 !N_M_LASER(ZV,RV,AV)

DO WHILE (NSZ1_LASER < NZ1_LASER)

   Z_E =  Z_LASER1 
  
   BE = 0.d0

   GA = 0.d0 

  
   IF (PACOTE==0) THEN

      PACOTE=1

      CALL RANDOM_NUMBER(R_AL)
      AL_E= R_AL*2.D0*PI

      CALL RANDOM_NUMBER(R_R)

      R_E = ( (DIMR_LASER1**2.D0)*R_R )**.5D0 

 
      CALL RANDOM_NUMBER(R_FI)
      FI = 0.d0 !2.D0*PI*R_FI ! ANGULO FI DE EMISSAO DO LASER (RADIACAO COLIMADA) 
      CALL RANDOM_NUMBER(R_TE)
      TE=  PI/2.D0 ! ANGULO TE DE EMISSAO DO LASER (RADIACAO COLIMADA) 
   
      !OBS: A COMBINACAO TE = PI/2.D0, FI = 0.D0, BE=0.D0 E GA=0.D0 RESULTA EM UM RAIO PERPENDICULAR À SUPERFÍCIE Z1
           
      CALL MRL(Z_E,R_E,AL_E,Z,R,AL,Z_LASER1,R_LASER1,AL_LASER1,BE_LASER1,GA_LASER1,TE,FI)

   
      INT_TEMP = INT(NR*R/DIMR)

      IF (R - INT_TEMP*DIMR/NR .GT. 0.D0 ) THEN 

         RV = INT_TEMP + 2

         ELSE 

         RV = INT_TEMP + 1

         IF (R .EQ. DIMR) THEN 

            RV = NR + 2
    
         ENDIF

      ENDIF

      INT_TEMP = INT(NZ*Z/DIMZ)

      IF (Z - INT_TEMP*DIMZ/NZ .GT. 0.D0 ) THEN 

         ZV = INT_TEMP + 2

         ELSE

         ZV = INT_TEMP + 1

         IF (Z .EQ. DIMZ) THEN 

            ZV = NZ + 2
    
         ENDIF

      ENDIF

 
      INT_TEMP =  INT(NA*AL/DIM_ALPHA)

      IF (AL - INT_TEMP*DIM_ALPHA/NA .GT. 0.D0 ) THEN 

         AV =  INT_TEMP + 1

         ELSE 

         AV =  INT_TEMP 

      ENDIF

      IF (AV .EQ. 0.d0) THEN
       
         AV = 1

      ENDIF

      CEE=0
      K_C=0.D0  

      CALL RANDOM_NUMBER(RANDCE)
      IF (RANDCE > (CE1+CE2)) THEN
         IF (RANDCE < (CE1+CE2+CE3)) THEN
            K_C=KC3
            CEE=CE3
         ENDIF
      ENDIF

      IF (RANDCE < (CE1+CE2)) THEN
         IF (RANDCE > CE1) THEN
            K_C=KC2
            CEE=CE2
         ELSE
            K_C=KC1
	    CEE=CE1
         ENDIF
      ENDIF


      EP=Q_LASER1/N_LASER1

      Z_E = Z
      R_E = R
      AL_E = AL

 
!   write(*,*)'ZV,AV,RV',ZV,AV,RV,AL
!pause


 !write(*,*)'AL1',AL
!pause

      CALL CHEGADA

 

!write(*,*)'Z_C,AL_C,R_C',Z_C,AL_C,R_C,TE_I,FI_I,R_E
!pause

   ENDIF

   CALL ABSORCAO_E_REFLEXAO(E_M,D_M,NANO_IN_VOLUME,CA_CINZA,CESP,CEXT,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,&
&G,N_TE,CPART,CTEC,QA,QS,raio)
 
! write(*,*)'ZV_A,AV_A,RV_A',ZV_A,AV_A,RV_A
!pause
    
   EMIT_M(ZV,RV,AV)= 0.D0 !EMIT_M(ZV,RV,AV)+EP
   EAB2(ZV_A,RV_A,AV_A)=EAB2(ZV_A,RV_A,AV_A)+EP

  
   !E_EMAB(ZV,RV,ZV_A,RV_A)=E_EMAB(ZV,RV,ZV_A,RV_A)+EP
   NSZ1_LASER=NSZ1_LASER+1


ENDDO



DO ZV=1,NZ+2
DO RV=1,NR+2
DO AV=1,NA
    
!OBS: colocar de volta 
WRITE(*,*)'LOCALIZACAO (ZV,RV,AV) DA EMISSAO',ZV,RV,AV


NSZ1=0
NSZ2=0
NSR=0
NSG=0
NS2=0
S11=0
S11_A=0
S12=0
S12_A=0
S21=0
S21_A=0
S22=0
S22_A=0
PACOTE=0
NR1=0
NR2=0
RVS=0
R2=0



IF (MIST==1) THEN
  ! 10% VAPOR DE AGUA E 10% DIOXIDO DE CARBONO 
   KC1=.4303D0*PWC
   KC2=7.055D0*PWC 
   KC3=178.1D0*PWC 
   CE1=5.150D-1-(2.303D-4)*T_M(ZV,RV,AV)+(.9779D-7)*T_M(ZV,RV,AV)**2-(1.494D-11)*T_M(ZV,RV,AV)**3
   CE2=0.7749D-1+(3.399D-4)*T_M(ZV,RV,AV)-(2.297D-7)*T_M(ZV,RV,AV)**2+(3.77D-11)*T_M(ZV,RV,AV)**3
   CE3=1.907D-1-(1.824D-4)*T_M(ZV,RV,AV)+(0.5608D-7)*T_M(ZV,RV,AV)**2-(0.5122D-11)*T_M(ZV,RV,AV)**3
ENDIF
IF (MIST==2) THEN 
  ! 20% VAPOR DE AGUA E 10% DIOXIDO DE CARBONO 
   KC1=.4201D0*PWC
   KC2=6.516D0*PWC
   KC3=131.9D0*PWC
   CE1=6.508D-1-(5.551D-4)*T_M(ZV,RV,AV)+(3.029D-7)*T_M(ZV,RV,AV)**2-(5.353D-11)*T_M(ZV,RV,AV)**3
   CE2=-0.2504D-1+(6.112D-4)*T_M(ZV,RV,AV)-(3.882D-7)*T_M(ZV,RV,AV)**2+(6.528D-11)*T_M(ZV,RV,AV)**3
   CE3=2.718D-1-(3.118D-4)*T_M(ZV,RV,AV)+(1.221D-7)*T_M(ZV,RV,AV)**2-(1.612D-11)*T_M(ZV,RV,AV)**3
ENDIF
IF (MIST==3) THEN
  ! SOMENTE DIOXIDO DE CARBONO 
   KC1=.3966D0*PC
   KC2=15.64D0*PC
   KC3=394.3D0*PC
   CE1=.4334D-1+(2.62D-4)*T_M(ZV,RV,AV)-(1.56D-7)*T_M(ZV,RV,AV)**2+(2.565D-11)*T_M(ZV,RV,AV)**3
   CE2=-0.4814D-1+(2.822D-4)*T_M(ZV,RV,AV)-(1.794D-7)*T_M(ZV,RV,AV)**2+(3.274D-11)*T_M(ZV,RV,AV)**3
   CE3=.5492D-1+(.1087D-4)*T_M(ZV,RV,AV)-(.35D-7)*T_M(ZV,RV,AV)**2+(0.9123D-11)*T_M(ZV,RV,AV)**3
ENDIF

IF (MIST==4) THEN
  ! SOMENTE VAPOR DE AGUA  
   KC1=.4098D0*PW
   KC2=6.325D0*PW
   KC3=120.5D0*PW
   CE1=5.977D-1-(5.119D-4)*T_M(ZV,RV,AV)+(3.042D-7)*T_M(ZV,RV,AV)**2-(5.564D-11)*T_M(ZV,RV,AV)**3
   CE2=.5677D-1+(3.333D-4)*T_M(ZV,RV,AV)-(1.967D-7)*T_M(ZV,RV,AV)**2+(2.718D-11)*T_M(ZV,RV,AV)**3
   CE3=1.8D-1-(2.334D-4)*T_M(ZV,RV,AV)+(1.008D-7)*T_M(ZV,RV,AV)**2-(1.454D-11)*T_M(ZV,RV,AV)**3
ENDIF

IF (MIST==5) THEN
  ! GAS CINZA 
   KC1=0.D0
   KC2=0.D0
   KC3=CA_CINZA(ZV,RV,AV)
   CE1=0.D0
   CE2=0.D0
   CE3=1.D0
ENDIF

! 1 EMISSAO E REFLEXAO DE PACOTES POR SUPERFICIES E GAS




! 1.2 EMISSAO DE PACOTES PELA SUPERFICIE Z1

NZ1=N_Z1_M(ZV,RV,AV)

DO WHILE (NSZ1<NZ1)
   Z=0.D0
   BE=0.D0
   GA=0.D0
  IF (PACOTE==0) THEN
      PACOTE=1
      CALL RANDOM_NUMBER(R_AL)
      AL=R_AL*2.D0*PI
      R1=(RV-2)*DELR
      R2=(RV-1)*DELR
	  CALL RANDOM_NUMBER(R_R)
      R=((R2**2.D0-R1**2.D0)*R_R+R1**2.D0)**.5D0
   	  CALL RANDOM_NUMBER(R_FI)
      FI=2.D0*PI*R_FI
	  CALL RANDOM_NUMBER(R_TE)
      TE=PI/2.D0-ASIN(R_TE**.5D0)
      CALL RANDOM_NUMBER(RANDCE)
      
      CEE=0
      K_C=1.D0  

IF (RANDCE > (CE1+CE2)) THEN
   IF (RANDCE < (CE1+CE2+CE3)) THEN
      K_C=KC3
      CEE=CE3
   ENDIF
ENDIF

IF (RANDCE < (CE1+CE2)) THEN
   IF (RANDCE > CE1) THEN
      K_C=KC2
      CEE=CE2
   ELSE
      K_C=KC1
	  CEE=CE1
   ENDIF
ENDIF

!K_ABS = K_C
!CEXT(ZV,RV,AV) = K_C + CESP(ZV,RV,AV)

      EP=E_M(ZV,RV,AV)*A_M(ZV,RV,AV)*5.67D-8*T_M(ZV,RV,AV)**4.D0/NZ1
	  
  
      Z_E=Z
      R_E=R
      AL_E=AL
      CALL CHEGADA
   ENDIF
   CALL ABSORCAO_E_REFLEXAO(E_M,D_M,NANO_IN_VOLUME,CA_CINZA,CESP,CEXT,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,&
&G,N_TE,CPART,CTEC,QA,QS,raio)


   EMIT_M(ZV,RV,AV)=EMIT_M(ZV,RV,AV)+EP
   EAB2(ZV_A,RV_A,AV_A)=EAB2(ZV_A,RV_A,AV_A)+EP
   !E_EMAB(ZV,RV,ZV_A,RV_A)=E_EMAB(ZV,RV,ZV_A,RV_A)+EP
   NSZ1=NSZ1+1

ENDDO


! 1.3 EMISSAO DE PACOTES PELA SUPERFICIE Z2

NZ2=N_Z2_M(ZV,RV,AV)
DO WHILE (NSZ2<NZ2)
   Z=DIMZ
   BE=PI
   GA=0.D0
   IF (PACOTE==0) THEN
      PACOTE=1
	  CALL RANDOM_NUMBER(R_AL)
      AL=R_AL*2.D0*PI
	  CALL RANDOM_NUMBER(R_R)
      R1=(RV-2)*DELR
      R2=(RV-1)*DELR
      R=((R2**2.D0-R1**2.D0)*R_R+R1**2.D0)**.5D0
	  CALL RANDOM_NUMBER(R_FI)
      FI=2.D0*PI*R_FI
	  CALL RANDOM_NUMBER(R_TE)
      TE=PI/2.D0-ASIN(R_TE**.5D0)


CALL RANDOM_NUMBER(RANDCE)

CEE=0
K_C=1.D0

IF (RANDCE > (CE1+CE2)) THEN
   IF (RANDCE < (CE1+CE2+CE3)) THEN
      K_C=KC3
      CEE=CE3
   ENDIF
ENDIF

IF (RANDCE < (CE1+CE2)) THEN
   IF (RANDCE > CE1) THEN
      K_C=KC2
      CEE=CE2
   ELSE
      K_C=KC1
	  CEE=CE1
   ENDIF
ENDIF

!K_ABS = K_C
!CEXT(ZV,RV,AV) = K_C + CESP(ZV,RV,AV)

      EP=E_M(ZV,RV,AV)*A_M(ZV,RV,AV)*5.67D-8*T_M(ZV,RV,AV)**4.D0/NZ2
      Z_E=Z
      R_E=R
      AL_E=AL
      CALL CHEGADA
   ENDIF
   CALL ABSORCAO_E_REFLEXAO(E_M,D_M,NANO_IN_VOLUME,CA_CINZA,CESP,CEXT,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,&
&G,N_TE,CPART,CTEC,QA,QS,raio)
   EMIT_M(ZV,RV,AV)=EMIT_M(ZV,RV,AV)+EP
   EAB2(ZV_A,RV_A,AV_A)=EAB2(ZV_A,RV_A,AV_A)+EP
   !E_EMAB(ZV,RV,ZV_A,RV_A)=E_EMAB(ZV,RV,ZV_A,RV_A)+EP
   NSZ2=NSZ2+1

ENDDO

! 1.4 EMISSAO DE PACOTES PELA SUPERFICIE R

NUMR=N_R_M(ZV,RV,AV)
DO WHILE(NSR<NUMR)
   R=DIMR
   BE=PI/2.D0
   IF (PACOTE==0) THEN
      PACOTE=1
         
 	  CALL RANDOM_NUMBER(R_Z)
      Z=(ZV-2)*DIMZ/NZ+(DIMZ/NZ)*R_Z
        
 	  CALL RANDOM_NUMBER(R_AL)
      AL=R_AL*2.D0*PI
      IF (AL<PI) THEN
         GA=AL+PI
      ENDIF
      IF (AL>=PI) THEN
         GA=AL-PI
      ENDIF
     
  	  CALL RANDOM_NUMBER(R_FI)
      FI=2.D0*PI*R_FI
  	  CALL RANDOM_NUMBER(R_TE)
   
      TE=PI/2.D0-ASIN(R_TE**.5D0)
	  

CALL RANDOM_NUMBER(RANDCE)
CEE=0
K_C=1.D0


IF (RANDCE > (CE1+CE2)) THEN
   IF (RANDCE < (CE1+CE2+CE3)) THEN
      K_C=KC3
      CEE=CE3
   ENDIF
ENDIF

IF (RANDCE < (CE1+CE2)) THEN
   IF (RANDCE > CE1) THEN
      K_C=KC2
      CEE=CE2
   ELSE
      K_C=KC1
	  CEE=CE1
   ENDIF
ENDIF

!K_ABS = K_C
!CEXT(ZV,RV,AV) = K_C + CESP(ZV,RV,AV)

      EP=E_M(ZV,RV,AV)*A_M(ZV,RV,AV)*5.67D-8*T_M(ZV,RV,AV)**4.D0/NUMR
      Z_E=Z
      R_E=R
      AL_E=AL
      CALL CHEGADA
   ENDIF
   CALL ABSORCAO_E_REFLEXAO(E_M,D_M,NANO_IN_VOLUME,CA_CINZA,CESP,CEXT,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,&
&G,N_TE,CPART,CTEC,QA,QS,raio)
   EMIT_M(ZV,RV,AV)=EMIT_M(ZV,RV,AV)+EP
   EAB2(ZV_A,RV_A,AV_A)=EAB2(ZV_A,RV_A,AV_A)+EP
   !E_EMAB(ZV,RV,ZV_A,RV_A)=E_EMAB(ZV,RV,ZV_A,RV_A)+EP
   NSR=NSR+1

ENDDO   


! 1.5 EMISSAO DE PACOTES PELO VOLUME DE GAS

NAL=0
NFI=0
NTE45=0
NTE=0
NG=N_G_M(ZV,RV,AV)
DO WHILE (NSG<NG) 
   IF (PACOTE==0) THEN
      PACOTE=1
      CALL RANDOM_NUMBER(R_TE)
      TE=PI/2D0-ACOS(1.D0-2.D0*R_TE)
      CALL RANDOM_NUMBER(R_FI)
      FI=2.D0*PI*R_FI
	  IF (R_FI<.5D0) THEN
	  NFI=NFI+1
	  ENDIF
      BE=0.D0
      GA=0.D0
      CALL RANDOM_NUMBER(R_Z)
      Z=(ZV-2)*DIMZ/NZ+(DIMZ/NZ)*R_Z
      R1=(RV-2)*DELR
      R2=(RV-1)*DELR
      CALL RANDOM_NUMBER(R_R)
      R=((R2**2.D0-R1**2.D0)*R_R+R1**2.D0)**.5D0
      CALL RANDOM_NUMBER(R_AL)
	  AL=R_AL*2.D0*PI
 	  IF (R_AL<.5D0) THEN
	  NAL=NAL+1
	  ENDIF
	  

CALL RANDOM_NUMBER(RANDCE)

CEE=0
K_C=1.D0

IF (RANDCE > (CE1+CE2)) THEN
   IF (RANDCE < (CE1+CE2+CE3)) THEN
      K_C=KC3
      CEE=CE3
   ENDIF
ENDIF

IF (RANDCE < (CE1+CE2)) THEN
   IF (RANDCE > CE1) THEN
      K_C=KC2
      CEE=CE2
   ELSE
      K_C=KC1
      CEE=CE1
   ENDIF
ENDIF

!K_ABS = K_C
!CEXT(ZV,RV,AV) = K_C + CESP(ZV,RV,AV)

EP=(4.D0*K_C*V_M(ZV,RV,AV)*5.67D-8*T_M(ZV,RV,AV)**4.D0)/NG


      Z_E=Z
      R_E=R
      AL_E=AL      
      CALL CHEGADA
   ENDIF

   CALL ABSORCAO_E_REFLEXAO(E_M,D_M,NANO_IN_VOLUME,CA_CINZA,CESP,CEXT,CESP_NANO,CABS_NANO,CEXT_NANO,R_N,FV,R_VC,FV_VC,&
&G,N_TE,CPART,CTEC,QA,QS,raio)

   EMIT_M(ZV,RV,AV)=EMIT_M(ZV,RV,AV)+EP
   EAB2(ZV_A,RV_A,AV_A)=EAB2(ZV_A,RV_A,AV_A)+EP
   !E_EMAB(ZV,RV,ZV_A,RV_A)=E_EMAB(ZV,RV,ZV_A,RV_A)+EP
   NSG=NSG+1

ENDDO  


ENDDO
ENDDO
ENDDO


END SUBROUTINE CILINDRO_NUCLEO


